// Code generated by wire-gen-go-provider. DO NOT EDIT.
// Matches '^func New' or '^type WireFieldsOf' per package.
package server

import (
	"github.com/google/wire"
)

var ProviderSet = wire.NewSet(
	NewApi,
	NewConsumer,
	NewConsumerRouter,
	NewGrpcServer,
	NewHttpServer,
	NewRpcxerver,
	NewScriptServer,
	NewWebsocket,
)
