// Code generated by wire-gen-go-provider. DO NOT EDIT.
// Matches '^func New' or '^type WireFieldsOf' per package.
package data

import (
	"github.com/google/wire"
)

var ProviderSet = wire.NewSet(
	NewUserRepo,
)
