// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/neo532/gofr"
	"github.com/neo532/gofr_layout/cmd"
	"github.com/neo532/gofr_layout/internal/server"
)

// Injectors from wire.go:

func initApp() (*gofr.App, func(), error) {
	context := cmd.BootContext()
	config, cleanup, err := cmd.InitConfig()
	if err != nil {
		return nil, nil, err
	}
	v := server.NewApi(config)
	app := newApp(context, config, v...)
	return app, func() {
		cleanup()
	}, nil
}
