// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/neo532/gofr"
	"github.com/neo532/gofr_layout/cmd"
	"github.com/neo532/gofr_layout/internal/biz"
	"github.com/neo532/gofr_layout/internal/connect"
	"github.com/neo532/gofr_layout/internal/data"
	"github.com/neo532/gofr_layout/internal/server"
	"github.com/neo532/gofr_layout/internal/service/api"
)

// Injectors from wire.go:

func initApp() (*gofr.App, func(), error) {
	context := cmd.BootContext()
	config, cleanup, err := cmd.InitConfig(context)
	if err != nil {
		return nil, nil, err
	}
	httpServer := server.NewHttpServer(config)
	grpcServer := server.NewGrpcServer(config)
	rpcxServer := server.NewRpcxerver(config)
	websocketServer := server.NewWebsocket(config)
	logger, cleanup2, err := cmd.InitLogger(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	wireFieldsOfDatabaseUserSet, cleanup3, err := connect.NewDatabaseUser(context, config, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	transactionUser := wireFieldsOfDatabaseUserSet.TX
	databaseUser := wireFieldsOfDatabaseUserSet.DB
	userRepo := data.NewUserRepo(databaseUser)
	producerUser, cleanup4, err := connect.NewProducerDefault(context, config, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userBiz := biz.NewUserBiz(transactionUser, userRepo, producerUser)
	userApi := api.NewUserApi(userBiz, logger)
	user1Api := api.NewUser1Api(logger)
	v := server.NewApi(httpServer, grpcServer, rpcxServer, websocketServer, userApi, user1Api)
	app := newApp(context, config, v...)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
