// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/neo532/gofr"
	"github.com/neo532/gofr_layout/internal/config"
	"github.com/neo532/gofr_layout/internal/server"
	"github.com/neo532/gokit/logger"
)

// Injectors from wire.go:

func initApp(contextContext context.Context, configConfig *config.Config, loggerLogger logger.Logger) (*gofr.App, func(), error) {
	v := server.NewApi(configConfig)
	app := newApp(contextContext, configConfig, v...)
	return app, func() {
	}, nil
}
