// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"github.com/neo532/gofr_layout/cmd"
	"github.com/neo532/gofr_layout/internal/data"
	"github.com/neo532/gofr_layout/internal/data/base"
	"github.com/neo532/gofr_layout/internal/domain"
	"github.com/neo532/gofr_layout/internal/service/api"
)

// Injectors from wire.go:

func UserApiService() (*api.UserApiService, func(), error) {
	context := cmd.BootContext()
	config, cleanup, err := cmd.InitConfig()
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup2, err := cmd.InitLogger(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	databaseDefault, cleanup3, err := base.NewDatabaseDefault(context, config, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	transactionDefaultRepo := data.NewTransactionDefaultRepo(databaseDefault)
	userRepo := data.NewUserRepo(databaseDefault)
	userDomain := domain.NewUserDomain(transactionDefaultRepo, userRepo)
	userApiService := api.NewUserApiService(userDomain)
	return userApiService, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
