// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"github.com/neo532/gofr_layout/cmd"
	"github.com/neo532/gofr_layout/internal/data"
	"github.com/neo532/gofr_layout/internal/data/connect"
	"github.com/neo532/gofr_layout/internal/domain"
	"github.com/neo532/gofr_layout/internal/service/api"
)

// Injectors from wire.go:

func UserApi() (*api.UserApi, func(), error) {
	context := cmd.BootContext()
	config, cleanup, err := cmd.InitConfig(context)
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup2, err := cmd.InitLogger(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	wireFieldsOfDatabaseUserSet, cleanup3, err := connect.NewDatabaseUser(context, config, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	transactionUser := wireFieldsOfDatabaseUserSet.TX
	databaseUser := wireFieldsOfDatabaseUserSet.DB
	userRepo := data.NewUserRepo(databaseUser)
	producerUser, cleanup4, err := connect.NewProducerDefault(context, config, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userDomain := domain.NewUserDomain(transactionUser, userRepo, producerUser)
	userApi := api.NewUserApi(userDomain, logger)
	return userApi, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
