// Code generated by wire-gen-go-provider. DO NOT EDIT.
// Matches '^func New' or '^type WireFieldsOf' per package.
package connect

import (
	"github.com/google/wire"
)

var ProviderSet = wire.NewSet(
	NewDatabaseUser,
	NewProducerDefault,
	NewRedisLock,
	wire.FieldsOf(new(*WireFieldsOfDatabaseUserSet), "DB", "TX"),
)
