// Code generated by config-gen-go-struct from data.yaml. DO NOT EDIT.

package config

import (
	"github.com/neo532/gokit/sync/atomicx"
	"gopkg.in/yaml.v3"
)

type DataConsumerDefaultCfg struct {
	Addrs  atomicx.Slice[string]  `yaml:"addrs"`  // []string
	Group  atomicx.Atomic[string] `yaml:"group"`  // string
	Name   atomicx.Atomic[string] `yaml:"name"`   // string
	Topics atomicx.Slice[string]  `yaml:"topics"` // []string
}

type DataConsumerGrayCfg struct {
	Addrs  atomicx.Slice[string]  `yaml:"addrs"`  // []string
	Group  atomicx.Atomic[string] `yaml:"group"`  // string
	Name   atomicx.Atomic[string] `yaml:"name"`   // string
	Topics atomicx.Slice[string]  `yaml:"topics"` // []string
}

type DataConsumerShadowCfg struct {
	Addrs  atomicx.Slice[string]  `yaml:"addrs"`  // []string
	Group  atomicx.Atomic[string] `yaml:"group"`  // string
	Name   atomicx.Atomic[string] `yaml:"name"`   // string
	Topics atomicx.Slice[string]  `yaml:"topics"` // []string
}

type DataConsumerConfCfg struct {
	ConsumerDefault DataConsumerDefaultCfg  `yaml:"_consumer_default"` // DataConsumerDefaultCfg
	ConsumerGray    DataConsumerGrayCfg     `yaml:"_consumer_gray"`    // DataConsumerGrayCfg
	ConsumerShadow  DataConsumerShadowCfg   `yaml:"_consumer_shadow"`  // DataConsumerShadowCfg
	MaxSlowtime     atomicx.Atomic[float64] `yaml:"max_slowtime"`      // float64
}

type DataConsumerUserCfg struct {
	ConsumerConf DataConsumerConfCfg `yaml:"_consumer_conf"` // DataConsumerConfCfg
}

type DataDatabaseMasterCfg struct {
	Dsn  atomicx.Atomic[string] `yaml:"dsn"`  // string
	Name atomicx.Atomic[string] `yaml:"name"` // string
}

type DataDatabaseShadowMasterCfg struct {
	Dsn  atomicx.Atomic[string] `yaml:"dsn"`  // string
	Name atomicx.Atomic[string] `yaml:"name"` // string
}

type DataDatabaseShadowSlaveCfg struct {
	Dsn  atomicx.Atomic[string] `yaml:"dsn"`  // string
	Name atomicx.Atomic[string] `yaml:"name"` // string
}

type DataDatabaseSlaveCfg struct {
	Dsn  atomicx.Atomic[string] `yaml:"dsn"`  // string
	Name atomicx.Atomic[string] `yaml:"name"` // string
}

type DataDatabaseConfCfg struct {
	DatabaseMaster       DataDatabaseMasterCfg       `yaml:"_database_master"`        // DataDatabaseMasterCfg
	DatabaseShadowMaster DataDatabaseShadowMasterCfg `yaml:"_database_shadow_master"` // DataDatabaseShadowMasterCfg
	DatabaseShadowSlave  DataDatabaseShadowSlaveCfg  `yaml:"_database_shadow_slave"`  // DataDatabaseShadowSlaveCfg
	DatabaseSlave        DataDatabaseSlaveCfg        `yaml:"_database_slave"`         // DataDatabaseSlaveCfg
	ConnMaxLifetime      atomicx.Atomic[int64]       `yaml:"conn_max_lifetime"`       // int64
	MaxIdleConns         atomicx.Atomic[int64]       `yaml:"max_idle_conns"`          // int64
	MaxOpenConns         atomicx.Atomic[int64]       `yaml:"max_open_conns"`          // int64
	MaxSlowtime          atomicx.Atomic[float64]     `yaml:"max_slowtime"`            // float64
	TablePrefix          atomicx.Atomic[string]      `yaml:"table_prefix"`            // string
}

type DataDatabaseBizCfg struct {
	DatabaseConf DataDatabaseConfCfg `yaml:"_database_conf"` // DataDatabaseConfCfg
}

type DataDatabaseUserCfg struct {
	DatabaseConf DataDatabaseConfCfg `yaml:"_database_conf"` // DataDatabaseConfCfg
}

type DataProducerDefaultCfg struct {
	Addrs atomicx.Slice[string]  `yaml:"addrs"` // []string
	Name  atomicx.Atomic[string] `yaml:"name"`  // string
	Topic atomicx.Atomic[string] `yaml:"topic"` // string
}

type DataProducerGrayCfg struct {
	Addrs atomicx.Slice[string]  `yaml:"addrs"` // []string
	Name  atomicx.Atomic[string] `yaml:"name"`  // string
	Topic atomicx.Atomic[string] `yaml:"topic"` // string
}

type DataProducerShadowCfg struct {
	Addrs atomicx.Slice[string]  `yaml:"addrs"` // []string
	Name  atomicx.Atomic[string] `yaml:"name"`  // string
	Topic atomicx.Atomic[string] `yaml:"topic"` // string
}

type DataProducerConfCfg struct {
	ProducerDefault DataProducerDefaultCfg `yaml:"_producer_default"` // DataProducerDefaultCfg
	ProducerGray    DataProducerGrayCfg    `yaml:"_producer_gray"`    // DataProducerGrayCfg
	ProducerShadow  DataProducerShadowCfg  `yaml:"_producer_shadow"`  // DataProducerShadowCfg
}

type DataProducerUserCfg struct {
	ProducerConf DataProducerConfCfg `yaml:"_producer_conf"` // DataProducerConfCfg
}

type DataRedisDefaultCfg struct {
	Addr     atomicx.Atomic[string] `yaml:"addr"`     // string
	Db       atomicx.Atomic[int64]  `yaml:"db"`       // int64
	Name     atomicx.Atomic[string] `yaml:"name"`     // string
	Password atomicx.Atomic[string] `yaml:"password"` // string
}

type DataRedisGrayCfg struct {
	Addr     atomicx.Atomic[string] `yaml:"addr"`     // string
	Db       atomicx.Atomic[int64]  `yaml:"db"`       // int64
	Name     atomicx.Atomic[string] `yaml:"name"`     // string
	Password atomicx.Atomic[string] `yaml:"password"` // string
}

type DataRedisShadowCfg struct {
	Addr     atomicx.Atomic[string] `yaml:"addr"`     // string
	Db       atomicx.Atomic[int64]  `yaml:"db"`       // int64
	Name     atomicx.Atomic[string] `yaml:"name"`     // string
	Password atomicx.Atomic[string] `yaml:"password"` // string
}

type DataRedisConfCfg struct {
	RedisDefault DataRedisDefaultCfg     `yaml:"_redis_default"` // DataRedisDefaultCfg
	RedisGray    DataRedisGrayCfg        `yaml:"_redis_gray"`    // DataRedisGrayCfg
	RedisShadow  DataRedisShadowCfg      `yaml:"_redis_shadow"`  // DataRedisShadowCfg
	MaxSlowtime  atomicx.Atomic[float64] `yaml:"max_slowtime"`   // float64
}

type DataRedisLockCfg struct {
	RedisConf DataRedisConfCfg `yaml:"_redis_conf"` // DataRedisConfCfg
}

type DataCfg struct {
	ConsumerUser DataConsumerUserCfg `yaml:"consumer_user"` // DataConsumerUserCfg
	DatabaseBiz  DataDatabaseBizCfg  `yaml:"database_biz"`  // DataDatabaseBizCfg
	DatabaseUser DataDatabaseUserCfg `yaml:"database_user"` // DataDatabaseUserCfg
	ProducerUser DataProducerUserCfg `yaml:"producer_user"` // DataProducerUserCfg
	RedisLock    DataRedisLockCfg    `yaml:"redis_lock"`    // DataRedisLockCfg
}

type ConfigData struct {
	Data DataCfg `yaml:"data"` // DataCfg
}

// Load parses config data and populates ConfigData.
// If c is nil, a new ConfigData is created.
// If c is non-nil, data is merged into c (existing keys are overwritten).
func LoadData(data []byte, c *ConfigData) error {
	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return err
	}
	if c == nil {
		c = &ConfigData{}
	}
	loadConfigData(raw, c)
	return nil
}

func loadDataConsumerDefaultCfg(raw map[string]any, c *DataConsumerDefaultCfg) {
	for k, v := range raw {
		switch k {
		case "addrs":
			if list, ok := v.([]any); ok {
				c.Addrs.Set(list)
			}
		case "group":
			switch s := v.(type) {
			case string:
				c.Group.Set(s)
			default:
				c.Group.Set("")
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		case "topics":
			if list, ok := v.([]any); ok {
				c.Topics.Set(list)
			}
		}
	}
}

func loadDataConsumerGrayCfg(raw map[string]any, c *DataConsumerGrayCfg) {
	for k, v := range raw {
		switch k {
		case "addrs":
			if list, ok := v.([]any); ok {
				c.Addrs.Set(list)
			}
		case "group":
			switch s := v.(type) {
			case string:
				c.Group.Set(s)
			default:
				c.Group.Set("")
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		case "topics":
			if list, ok := v.([]any); ok {
				c.Topics.Set(list)
			}
		}
	}
}

func loadDataConsumerShadowCfg(raw map[string]any, c *DataConsumerShadowCfg) {
	for k, v := range raw {
		switch k {
		case "addrs":
			if list, ok := v.([]any); ok {
				c.Addrs.Set(list)
			}
		case "group":
			switch s := v.(type) {
			case string:
				c.Group.Set(s)
			default:
				c.Group.Set("")
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		case "topics":
			if list, ok := v.([]any); ok {
				c.Topics.Set(list)
			}
		}
	}
}

func loadDataConsumerConfCfg(raw map[string]any, c *DataConsumerConfCfg) {
	for k, v := range raw {
		switch k {
		case "_consumer_default":
			if m, ok := v.(map[string]any); ok {
				loadDataConsumerDefaultCfg(m, &c.ConsumerDefault)
			}
		case "_consumer_gray":
			if m, ok := v.(map[string]any); ok {
				loadDataConsumerGrayCfg(m, &c.ConsumerGray)
			}
		case "_consumer_shadow":
			if m, ok := v.(map[string]any); ok {
				loadDataConsumerShadowCfg(m, &c.ConsumerShadow)
			}
		case "max_slowtime":
			switch n := v.(type) {
			case float64:
				c.MaxSlowtime.Set(n)
			case int:
				c.MaxSlowtime.Set(float64(n))
			case int64:
				c.MaxSlowtime.Set(float64(n))
			}
		}
	}
}

func loadDataConsumerUserCfg(raw map[string]any, c *DataConsumerUserCfg) {
	for k, v := range raw {
		switch k {
		case "_consumer_conf":
			if m, ok := v.(map[string]any); ok {
				loadDataConsumerConfCfg(m, &c.ConsumerConf)
			}
		}
	}
}

func loadDataDatabaseMasterCfg(raw map[string]any, c *DataDatabaseMasterCfg) {
	for k, v := range raw {
		switch k {
		case "dsn":
			switch s := v.(type) {
			case string:
				c.Dsn.Set(s)
			default:
				c.Dsn.Set("")
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		}
	}
}

func loadDataDatabaseShadowMasterCfg(raw map[string]any, c *DataDatabaseShadowMasterCfg) {
	for k, v := range raw {
		switch k {
		case "dsn":
			switch s := v.(type) {
			case string:
				c.Dsn.Set(s)
			default:
				c.Dsn.Set("")
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		}
	}
}

func loadDataDatabaseShadowSlaveCfg(raw map[string]any, c *DataDatabaseShadowSlaveCfg) {
	for k, v := range raw {
		switch k {
		case "dsn":
			switch s := v.(type) {
			case string:
				c.Dsn.Set(s)
			default:
				c.Dsn.Set("")
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		}
	}
}

func loadDataDatabaseSlaveCfg(raw map[string]any, c *DataDatabaseSlaveCfg) {
	for k, v := range raw {
		switch k {
		case "dsn":
			switch s := v.(type) {
			case string:
				c.Dsn.Set(s)
			default:
				c.Dsn.Set("")
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		}
	}
}

func loadDataDatabaseConfCfg(raw map[string]any, c *DataDatabaseConfCfg) {
	for k, v := range raw {
		switch k {
		case "_database_master":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseMasterCfg(m, &c.DatabaseMaster)
			}
		case "_database_shadow_master":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseShadowMasterCfg(m, &c.DatabaseShadowMaster)
			}
		case "_database_shadow_slave":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseShadowSlaveCfg(m, &c.DatabaseShadowSlave)
			}
		case "_database_slave":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseSlaveCfg(m, &c.DatabaseSlave)
			}
		case "conn_max_lifetime":
			switch n := v.(type) {
			case int:
				c.ConnMaxLifetime.Set(int64(n))
			case int64:
				c.ConnMaxLifetime.Set(n)
			}
		case "max_idle_conns":
			switch n := v.(type) {
			case int:
				c.MaxIdleConns.Set(int64(n))
			case int64:
				c.MaxIdleConns.Set(n)
			}
		case "max_open_conns":
			switch n := v.(type) {
			case int:
				c.MaxOpenConns.Set(int64(n))
			case int64:
				c.MaxOpenConns.Set(n)
			}
		case "max_slowtime":
			switch n := v.(type) {
			case float64:
				c.MaxSlowtime.Set(n)
			case int:
				c.MaxSlowtime.Set(float64(n))
			case int64:
				c.MaxSlowtime.Set(float64(n))
			}
		case "table_prefix":
			switch s := v.(type) {
			case string:
				c.TablePrefix.Set(s)
			default:
				c.TablePrefix.Set("")
			}
		}
	}
}

func loadDataDatabaseBizCfg(raw map[string]any, c *DataDatabaseBizCfg) {
	for k, v := range raw {
		switch k {
		case "_database_conf":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseConfCfg(m, &c.DatabaseConf)
			}
		}
	}
}

func loadDataDatabaseUserCfg(raw map[string]any, c *DataDatabaseUserCfg) {
	for k, v := range raw {
		switch k {
		case "_database_conf":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseConfCfg(m, &c.DatabaseConf)
			}
		}
	}
}

func loadDataProducerDefaultCfg(raw map[string]any, c *DataProducerDefaultCfg) {
	for k, v := range raw {
		switch k {
		case "addrs":
			if list, ok := v.([]any); ok {
				c.Addrs.Set(list)
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		case "topic":
			switch s := v.(type) {
			case string:
				c.Topic.Set(s)
			default:
				c.Topic.Set("")
			}
		}
	}
}

func loadDataProducerGrayCfg(raw map[string]any, c *DataProducerGrayCfg) {
	for k, v := range raw {
		switch k {
		case "addrs":
			if list, ok := v.([]any); ok {
				c.Addrs.Set(list)
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		case "topic":
			switch s := v.(type) {
			case string:
				c.Topic.Set(s)
			default:
				c.Topic.Set("")
			}
		}
	}
}

func loadDataProducerShadowCfg(raw map[string]any, c *DataProducerShadowCfg) {
	for k, v := range raw {
		switch k {
		case "addrs":
			if list, ok := v.([]any); ok {
				c.Addrs.Set(list)
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		case "topic":
			switch s := v.(type) {
			case string:
				c.Topic.Set(s)
			default:
				c.Topic.Set("")
			}
		}
	}
}

func loadDataProducerConfCfg(raw map[string]any, c *DataProducerConfCfg) {
	for k, v := range raw {
		switch k {
		case "_producer_default":
			if m, ok := v.(map[string]any); ok {
				loadDataProducerDefaultCfg(m, &c.ProducerDefault)
			}
		case "_producer_gray":
			if m, ok := v.(map[string]any); ok {
				loadDataProducerGrayCfg(m, &c.ProducerGray)
			}
		case "_producer_shadow":
			if m, ok := v.(map[string]any); ok {
				loadDataProducerShadowCfg(m, &c.ProducerShadow)
			}
		}
	}
}

func loadDataProducerUserCfg(raw map[string]any, c *DataProducerUserCfg) {
	for k, v := range raw {
		switch k {
		case "_producer_conf":
			if m, ok := v.(map[string]any); ok {
				loadDataProducerConfCfg(m, &c.ProducerConf)
			}
		}
	}
}

func loadDataRedisDefaultCfg(raw map[string]any, c *DataRedisDefaultCfg) {
	for k, v := range raw {
		switch k {
		case "addr":
			switch s := v.(type) {
			case string:
				c.Addr.Set(s)
			default:
				c.Addr.Set("")
			}
		case "db":
			switch n := v.(type) {
			case int:
				c.Db.Set(int64(n))
			case int64:
				c.Db.Set(n)
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		case "password":
			switch s := v.(type) {
			case string:
				c.Password.Set(s)
			default:
				c.Password.Set("")
			}
		}
	}
}

func loadDataRedisGrayCfg(raw map[string]any, c *DataRedisGrayCfg) {
	for k, v := range raw {
		switch k {
		case "addr":
			switch s := v.(type) {
			case string:
				c.Addr.Set(s)
			default:
				c.Addr.Set("")
			}
		case "db":
			switch n := v.(type) {
			case int:
				c.Db.Set(int64(n))
			case int64:
				c.Db.Set(n)
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		case "password":
			switch s := v.(type) {
			case string:
				c.Password.Set(s)
			default:
				c.Password.Set("")
			}
		}
	}
}

func loadDataRedisShadowCfg(raw map[string]any, c *DataRedisShadowCfg) {
	for k, v := range raw {
		switch k {
		case "addr":
			switch s := v.(type) {
			case string:
				c.Addr.Set(s)
			default:
				c.Addr.Set("")
			}
		case "db":
			switch n := v.(type) {
			case int:
				c.Db.Set(int64(n))
			case int64:
				c.Db.Set(n)
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		case "password":
			switch s := v.(type) {
			case string:
				c.Password.Set(s)
			default:
				c.Password.Set("")
			}
		}
	}
}

func loadDataRedisConfCfg(raw map[string]any, c *DataRedisConfCfg) {
	for k, v := range raw {
		switch k {
		case "_redis_default":
			if m, ok := v.(map[string]any); ok {
				loadDataRedisDefaultCfg(m, &c.RedisDefault)
			}
		case "_redis_gray":
			if m, ok := v.(map[string]any); ok {
				loadDataRedisGrayCfg(m, &c.RedisGray)
			}
		case "_redis_shadow":
			if m, ok := v.(map[string]any); ok {
				loadDataRedisShadowCfg(m, &c.RedisShadow)
			}
		case "max_slowtime":
			switch n := v.(type) {
			case float64:
				c.MaxSlowtime.Set(n)
			case int:
				c.MaxSlowtime.Set(float64(n))
			case int64:
				c.MaxSlowtime.Set(float64(n))
			}
		}
	}
}

func loadDataRedisLockCfg(raw map[string]any, c *DataRedisLockCfg) {
	for k, v := range raw {
		switch k {
		case "_redis_conf":
			if m, ok := v.(map[string]any); ok {
				loadDataRedisConfCfg(m, &c.RedisConf)
			}
		}
	}
}

func loadDataCfg(raw map[string]any, c *DataCfg) {
	for k, v := range raw {
		switch k {
		case "consumer_user":
			if m, ok := v.(map[string]any); ok {
				loadDataConsumerUserCfg(m, &c.ConsumerUser)
			}
		case "database_biz":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseBizCfg(m, &c.DatabaseBiz)
			}
		case "database_user":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseUserCfg(m, &c.DatabaseUser)
			}
		case "producer_user":
			if m, ok := v.(map[string]any); ok {
				loadDataProducerUserCfg(m, &c.ProducerUser)
			}
		case "redis_lock":
			if m, ok := v.(map[string]any); ok {
				loadDataRedisLockCfg(m, &c.RedisLock)
			}
		}
	}
}

func loadConfigData(raw map[string]any, c *ConfigData) {
	for k, v := range raw {
		switch k {
		case "data":
			if m, ok := v.(map[string]any); ok {
				loadDataCfg(m, &c.Data)
			}
		}
	}
}
