// Code generated by config-gen-go-struct from general.yaml. DO NOT EDIT.

package config

import (
	"github.com/neo532/gokit/sync/atomicx"
	"gopkg.in/yaml.v3"
)

type GeneralLoggerCfg struct {
	Compress  atomicx.Atomic[bool]   `yaml:"compress"`   // bool
	Filename  atomicx.Atomic[string] `yaml:"filename"`   // string
	Level     atomicx.Atomic[string] `yaml:"level"`      // string
	MaxAge    atomicx.Atomic[int64]  `yaml:"max_age"`    // int64
	MaxBackup atomicx.Atomic[int64]  `yaml:"max_backup"` // int64
	MaxSize   atomicx.Atomic[int64]  `yaml:"max_size"`   // int64
}

type GeneralCfg struct {
	Entry   atomicx.Atomic[string] `yaml:"entry"`   // string
	Env     atomicx.Atomic[string] `yaml:"env"`     // string
	Ip      atomicx.Atomic[string] `yaml:"ip"`      // string
	Logger  GeneralLoggerCfg       `yaml:"logger"`  // GeneralLoggerCfg
	Name    atomicx.Atomic[string] `yaml:"name"`    // string
	Version atomicx.Atomic[string] `yaml:"version"` // string
}

type ConfigGeneral struct {
	General GeneralCfg `yaml:"general"` // GeneralCfg
}

// Load parses config data and populates ConfigGeneral.
// If c is nil, a new ConfigGeneral is created.
// If c is non-nil, data is merged into c (existing keys are overwritten).
func LoadGeneral(data []byte, c *ConfigGeneral) error {
	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return err
	}
	if c == nil {
		c = &ConfigGeneral{}
	}
	loadConfigGeneral(raw, c)
	return nil
}

func loadGeneralLoggerCfg(raw map[string]any, c *GeneralLoggerCfg) {
	for k, v := range raw {
		switch k {
		case "compress":
			if b, ok := v.(bool); ok {
				c.Compress.Set(b)
			}
		case "filename":
			switch s := v.(type) {
			case string:
				c.Filename.Set(s)
			default:
				c.Filename.Set("")
			}
		case "level":
			switch s := v.(type) {
			case string:
				c.Level.Set(s)
			default:
				c.Level.Set("")
			}
		case "max_age":
			switch n := v.(type) {
			case int:
				c.MaxAge.Set(int64(n))
			case int64:
				c.MaxAge.Set(n)
			}
		case "max_backup":
			switch n := v.(type) {
			case int:
				c.MaxBackup.Set(int64(n))
			case int64:
				c.MaxBackup.Set(n)
			}
		case "max_size":
			switch n := v.(type) {
			case int:
				c.MaxSize.Set(int64(n))
			case int64:
				c.MaxSize.Set(n)
			}
		}
	}
}

func loadGeneralCfg(raw map[string]any, c *GeneralCfg) {
	for k, v := range raw {
		switch k {
		case "entry":
			switch s := v.(type) {
			case string:
				c.Entry.Set(s)
			default:
				c.Entry.Set("")
			}
		case "env":
			switch s := v.(type) {
			case string:
				c.Env.Set(s)
			default:
				c.Env.Set("")
			}
		case "ip":
			switch s := v.(type) {
			case string:
				c.Ip.Set(s)
			default:
				c.Ip.Set("")
			}
		case "logger":
			if m, ok := v.(map[string]any); ok {
				loadGeneralLoggerCfg(m, &c.Logger)
			}
		case "name":
			switch s := v.(type) {
			case string:
				c.Name.Set(s)
			default:
				c.Name.Set("")
			}
		case "version":
			switch s := v.(type) {
			case string:
				c.Version.Set(s)
			default:
				c.Version.Set("")
			}
		}
	}
}

func loadConfigGeneral(raw map[string]any, c *ConfigGeneral) {
	for k, v := range raw {
		switch k {
		case "general":
			if m, ok := v.(map[string]any); ok {
				loadGeneralCfg(m, &c.General)
			}
		}
	}
}
