// Code generated by config-gen-go-struct from general.yaml. DO NOT EDIT.

package config

import (
	"github.com/neo532/gokit/sync/atomicx"
	"gopkg.in/yaml.v3"
)

type GeneralLoggerCfg struct {
	Compress  atomicx.Atomic[bool]   `yaml:"compress"`   // bool
	Filename  atomicx.Atomic[string] `yaml:"filename"`   // string
	Level     atomicx.Atomic[string] `yaml:"level"`      // string
	MaxAge    atomicx.Atomic[int64]  `yaml:"max_age"`    // int64
	MaxBackup atomicx.Atomic[int64]  `yaml:"max_backup"` // int64
	MaxSize   atomicx.Atomic[int64]  `yaml:"max_size"`   // int64
}

type GeneralCfg struct {
	Entry   atomicx.Atomic[string] `yaml:"entry"`   // string
	Env     atomicx.Atomic[string] `yaml:"env"`     // string
	Ip      atomicx.Atomic[string] `yaml:"ip"`      // string
	Logger  GeneralLoggerCfg       `yaml:"logger"`  // GeneralLoggerCfg
	Name    atomicx.Atomic[string] `yaml:"name"`    // string
	Version atomicx.Atomic[string] `yaml:"version"` // string
}

type ConfigGeneral struct {
	General GeneralCfg `yaml:"general"` // GeneralCfg
}

// Load parses config data and populates ConfigGeneral.
// If c is nil, a new ConfigGeneral is created.
// If c is non-nil, data is merged into c (existing keys are overwritten).
func LoadGeneral(data []byte, c *ConfigGeneral) error {
	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return err
	}
	if c == nil {
		c = &ConfigGeneral{}
	}
	loadConfigGeneral(raw, c)
	return nil
}

func loadGeneralLoggerCfg(raw map[string]any, c *GeneralLoggerCfg) {
	for k, v := range raw {
		switch k {
		case "compress":
			c.Compress.SetAny(v)
		case "filename":
			c.Filename.SetAny(v)
		case "level":
			c.Level.SetAny(v)
		case "max_age":
			c.MaxAge.SetAny(v)
		case "max_backup":
			c.MaxBackup.SetAny(v)
		case "max_size":
			c.MaxSize.SetAny(v)
		}
	}
}

func loadGeneralCfg(raw map[string]any, c *GeneralCfg) {
	for k, v := range raw {
		switch k {
		case "entry":
			c.Entry.SetAny(v)
		case "env":
			c.Env.SetAny(v)
		case "ip":
			c.Ip.SetAny(v)
		case "logger":
			if m, ok := v.(map[string]any); ok {
				loadGeneralLoggerCfg(m, &c.Logger)
			}
		case "name":
			c.Name.SetAny(v)
		case "version":
			c.Version.SetAny(v)
		}
	}
}

func loadConfigGeneral(raw map[string]any, c *ConfigGeneral) {
	for k, v := range raw {
		switch k {
		case "general":
			if m, ok := v.(map[string]any); ok {
				loadGeneralCfg(m, &c.General)
			}
		}
	}
}
