// Code generated by wire-gen-go-provider. DO NOT EDIT.
// Matches '^func New' or '^type WireFieldsOf' per package.
package v1

import (
	"github.com/google/wire"
)

var ProviderSet = wire.NewSet(
	NewUser1ApiGRPCClient,
	NewUser1ApiHTTPClient,
	NewUser1ApiRPCXClient,
	NewUser1ApiWSClient,
	NewUserApiGRPCClient,
	NewUserApiHTTPClient,
	NewUserApiRPCXClient,
	NewUserApiWSClient,
)
